### ISSUE TITLE
character validation

### ISSUE THREAD

**Issue by repins267** [rndinfosecguy/TrashSearch#3]
When I try to add special characters or numbers for a value ie:password search I get "TrashSearch.py: error: unrecognized arguments:" Specifically if I end the value with a number.

python3 TrashSearch.py -m 1 --value logrhythm!

**Comment by rndinfosecguy** [comment]
I think this is maybe a bash problem when calling the program.
Try python3 TrashSearch.py -m 1 --value "logrhythm!"
